FROM node:16-alpine

WORKDIR /app

COPY ./public ./public
COPY ./dist ./dist
COPY ./package.json ./package.json
COPY ./views ./views

RUN npm install

EXPOSE 80

ENTRYPOINT [ "node", "./dist/index.js" ]