FROM adoptopenjdk/openjdk11:alpine

WORKDIR /app

COPY ./jvm/build/libs/codegarten-0.1.jar ./codegarten.jar
COPY ./jvm/secrets-example ./secrets

EXPOSE 8080

ENTRYPOINT [ "java", "-server", "-jar", "codegarten.jar" ]