DELETE FROM DELIVERY;
DELETE FROM USER_ASSIGNMENT;
DELETE FROM ASSIGNMENT;
DELETE FROM USER_CLASSROOM;
DELETE FROM CLASSROOM;
DELETE FROM USERS;
DELETE FROM CLIENT;
DELETE FROM AUTHCODE;
DELETE FROM ACCESSTOKEN;

DROP TRIGGER IF EXISTS trig_create_classroom_seq ON CLASSROOM;
DROP TRIGGER IF EXISTS trig_cleanup_classroom_seq ON CLASSROOM;
DROP TRIGGER IF EXISTS trig_get_assignment_number ON ASSIGNMENT;
DROP TRIGGER IF EXISTS trig_cleanup_assignment_seq ON ASSIGNMENT;
DROP TRIGGER IF EXISTS trig_get_delivery_number ON DELIVERY;

DROP FUNCTION IF EXISTS func_create_classroom_seq;
DROP FUNCTION IF EXISTS func_cleanup_classroom_seq;
DROP FUNCTION IF EXISTS func_get_assignment_number;
DROP FUNCTION IF EXISTS func_cleanup_assignment_seq;
DROP FUNCTION IF EXISTS func_get_delivery_number;

DROP VIEW IF EXISTS V_DELIVERY;
DROP VIEW IF EXISTS V_ASSIGNMENT;

DROP TABLE IF EXISTS ACCESSTOKEN;
DROP TABLE IF EXISTS AUTHCODE;
DROP TABLE IF EXISTS CLIENT;
DROP TABLE IF EXISTS DELIVERY;
DROP TABLE IF EXISTS USER_ASSIGNMENT;
DROP TABLE IF EXISTS ASSIGNMENT;
DROP TABLE IF EXISTS USER_CLASSROOM;
DROP TABLE IF EXISTS CLASSROOM;
DROP TABLE IF EXISTS USERS;