DROP VIEW IF EXISTS V_ASSIGNMENT;
DROP VIEW IF EXISTS V_DELIVERY;

DROP TABLE IF EXISTS ACCESSTOKEN;
DROP TABLE IF EXISTS AUTHCODE;
DROP TABLE IF EXISTS CLIENT;
DROP TABLE IF EXISTS DELIVERY;
DROP TABLE IF EXISTS USER_ASSIGNMENT;
DROP TABLE IF EXISTS ASSIGNMENT;
DROP TABLE IF EXISTS USER_CLASSROOM;
DROP TABLE IF EXISTS CLASSROOM;
DROP TABLE IF EXISTS USERS;