DELETE FROM ACCESSTOKEN;
DELETE FROM AUTHCODE;
DELETE FROM CLIENT;
DELETE FROM DELIVERY;
DELETE FROM USER_ASSIGNMENT;
DELETE FROM ASSIGNMENT;
DELETE FROM USER_CLASSROOM;
DELETE FROM CLASSROOM;
DELETE FROM INSTALLATION;
DELETE FROM USERS;

DROP TRIGGER IF EXISTS trig_create_installation_seq ON INSTALLATION;
DROP TRIGGER IF EXISTS trig_cleanup_installation_seq ON INSTALLATION;
DROP TRIGGER IF EXISTS trig_create_classroom_seq ON CLASSROOM;
DROP TRIGGER IF EXISTS trig_cleanup_classroom_seq ON CLASSROOM;
DROP TRIGGER IF EXISTS trig_get_assignment_number ON ASSIGNMENT;
DROP TRIGGER IF EXISTS trig_cleanup_assignment_seq ON ASSIGNMENT;
DROP TRIGGER IF EXISTS trig_get_delivery_number ON DELIVERY;

DROP FUNCTION IF EXISTS func_create_installation_seq;
DROP FUNCTION IF EXISTS func_cleanup_installation_seq;
DROP FUNCTION IF EXISTS func_create_classroom_seq;
DROP FUNCTION IF EXISTS func_cleanup_classroom_seq;
DROP FUNCTION IF EXISTS func_get_assignment_number;
DROP FUNCTION IF EXISTS func_cleanup_assignment_seq;
DROP FUNCTION IF EXISTS func_get_delivery_number;

DROP VIEW IF EXISTS V_DELIVERY;
DROP VIEW IF EXISTS V_ASSIGNMENT;
DROP VIEW IF EXISTS V_USER_CLASSROOM;
DROP VIEW IF EXISTS V_USER;

DROP TABLE IF EXISTS ACCESSTOKEN;
DROP TABLE IF EXISTS AUTHCODE;
DROP TABLE IF EXISTS CLIENT;
DROP TABLE IF EXISTS DELIVERY;
DROP TABLE IF EXISTS USER_ASSIGNMENT;
DROP TABLE IF EXISTS ASSIGNMENT;
DROP TABLE IF EXISTS USER_CLASSROOM;
DROP TABLE IF EXISTS CLASSROOM;
DROP TABLE IF EXISTS INSTALLATION;
DROP TABLE IF EXISTS USERS;