version: "3.3"
services:
  codegarten-server:
    container_name: codegarten-server
    build:
      context: ../code/jvm
      dockerfile: Dockerfile
    env_file: ./env_server
    environment:
      - JDBC_DATABASE_URL=jdbc:postgresql://codegarten-db:5432/db?user=codegarten&password=changeit
      - CODEGARTEN_TEST_DB_CONNECTION_STRING=jdbc:postgresql://codegarten-db-tests:5433/db?user=codegarten&password=changeit
    depends_on:
      - codegarten-db
      - codegarten-db-tests
    ports:
      - 8080:8080
  codegarten-web:
    container_name: codegarten-web
    build:
      context: ../code/js
      dockerfile: Dockerfile
    env_file: ./env_web
    environment:
      - CG_SERVER_API_HOST=http://codegarten-server:8080
      - CG_SERVER_IM_HOST=http://localhost:8080
    depends_on:
      - codegarten-server
    ports:
      - 80:80
  codegarten-db:
    container_name: codegarten-db
    build:
      context: ../code
      dockerfile: jvm/tests/Dockerfile-codegarten-db
    environment:
      - POSTGRES_USER=codegarten
      - POSTGRES_PASSWORD=changeit
      - POSTGRES_DB=db
    ports:
      - 5432:5432
  codegarten-db-tests:
    container_name: codegarten-db-tests
    build:
      context: ../code
      dockerfile: jvm/tests/Dockerfile-codegarten-db-tests
    environment:
      - POSTGRES_USER=codegarten
      - POSTGRES_PASSWORD=changeit
      - POSTGRES_DB=db
    ports:
      - 5433:5432