version: "3.3"
services:
  codegarten-db:
    container_name: codegarten-db
    build:
      context: ..
      dockerfile: jvm/tests/Dockerfile-codegarten-db
    environment:
      - POSTGRES_USER=codegarten
      - POSTGRES_PASSWORD=changeit
      - POSTGRES_DB=db
    ports:
      - 5432:5432
  codegarten-db-tests:
    container_name: codegarten-db-tests
    build:
      context: ..
      dockerfile: jvm/tests/Dockerfile-codegarten-db-tests
    environment:
      - POSTGRES_USER=codegarten
      - POSTGRES_PASSWORD=changeit
      - POSTGRES_DB=db
    ports:
      - 5433:5432
  codegarten-server-app:
    container_name: codegarten-server-app
    build:
      context: ..
      dockerfile:  jvm/tests/Dockerfile-codegarten-server-app
    depends_on: [ codegarten-db ]
    ports:
      - 8080:8080
    environment: 
      - CODEGARTEN_DB_CONNECTION_STRING=jdbc:postgresql://codegarten-db:5432/db?user=codegarten&password=changeit
      - CODEGARTEN_GITHUB_APP_PROPERTIES_PATH=secrets-example/github-app-properties.json
      - CODEGARTEN_GITHUB_APP_PRIVATE_KEY_PATH=secrets-example/gh-app-private-key.pem
      - CODEGARTEN_CIPHER_KEY_PATH=secrets-example/cipher-key.txt