name: Continuous Integration

on: [push]

jobs:
  build:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Gradle
        env:
          JDBC_CONNECTION_URL: jdbc:postgresql://localhost:5432/db?user=codegarten&password=changeit
          CODEGARTEN_TEST_DB_CONNECTION_STRING: jdbc:postgresql://localhost:5433/db?user=codegarten&password=changeit
          CODEGARTEN_GITHUB_APP_PROPERTIES: ewogICAgIm5hbWUiOiAiR2l0SHViIEFwcCBOYW1lIiwKICAgICJpZCI6IDEyMzQsCiAgICAiY2xpZW50SWQiOiAiVGhlIENsaWVudCBJRCIsCiAgICAiY2xpZW50U2VjcmV0IjogIlRoZSBDbGllbnQgU2VjcmV0Igp9
          CODEGARTEN_GITHUB_APP_PRIVATE_KEY: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlDWEFJQkFBS0JnUUNUSjJJTmU3UURCUkFoRHpFQ096c2Q5ZW9OR3VZd0l2NmNENENFbDdDcDVxTlBtNFBqClBRenQwemE3QTZuN04vVGZHZGJxcVlCWU43RzhDWXQ1VDQzbStEMW9mRmJaeC8wenROU3BkdkNEcGNSdHYzS0IKcjdlM2xOL0dGNkpQd3EyNlJZR0lTNFRwTFBJZkZBVFA4SUFpS3AraHVJMkt4S1MzK3psamdvM3Urd0lEQVFBQgpBb0dBZlVGQWpRbUdxQ3RmRjBTL0NvOHdPc2hmZU5nMHB6U2lWR1E5bUo4bG1QamdlWnArSUthT29zRHVEVEdKCk5uVGkwaVJFYzJuai9UTXE3a3VSbEtqS3QweUk1M29FSzNMbjBMV1dJQUh4cXFjNWg0ZGNmYWRmM2ZpRlhHbmkKSG0vKzU5U2JmTFBaajFCcUhtTFQ2ckpUWFptRkE1ck5TTTgyMzJDbFh1cW1rd0VDUVFER0V5ZXhGOVFSdXBhYwpaMGQ4NUttVFFFOW10NWQ5OERVS1g5WktPSDJPWjhuVzdOZEtrUytBTzlPQTl3L2RiRTcrTTBXcmJ3a05OTTlICnV1L1pzVlhyQWtFQXZqQUpETlhzcll0VFdkR01BMHBRKzFTNlRLdDQ2c0JBdjkxKzRHYVd3WTZodldOMEJzSzgKVHhaWGpwQnNZSG8zeUJNV0wrdEdnN1crWDR2UlBiVTNNUUpBRzFjTmhYNDZnVy8xMWdUVGMwUEV2RlNHSVRGNgpNYUgwVUVoR05keHlTRE8vUW5GU2pqSllFaVV2M244N3ExNkYwTVNXKzBES1NRNWZCaEdoaGJUYW5RSkJBSnE0CjhXUGoxVHdLRUxFTmJGNXc0eGpVZ1F0R3BJUTJDM2NMZHVDUUZTMDZJQkszQ2ZsR0MzUTd0TmRpWHdqTjVQdDcKcTUwb1JxRjRCWHd0ZnZnNHFNRUNRRGM2M1JZeVdndkVGZWFIRExVR1htMlFPa3Z1Q0kreEtpMWF0eHpnVnpXWgpmblhRR2NFZ3VwOGZzZXdhWld0Zy9xWnFUeDAxNklxbTRHcmE3d2gxOTNNPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQoKVGhlIGFib3ZlIGtleSBpcyBtZXJlbHkgYSBkdW1teSBrZXkuIFBsZWFzZSByZXBsYWNlIGl0IHdpdGggeW91ciBvd24u
          CODEGARTEN_CIPHER_KEY: cipherkeywith16-24-32bytes
        run: code/jvm/gradlew -p code/jvm test
