name: Continuous Integration

on: [push]

jobs:
  build:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Gradle
        env:
          JDBC_CONNECTION_URL: jdbc:postgresql://localhost:5432/db?user=codegarten&password=changeit
          CODEGARTEN_TEST_DB_CONNECTION_STRING: jdbc:postgresql://localhost:5433/db?user=codegarten&password=changeit
          CODEGARTEN_GITHUB_APP_PROPERTIES_PATH: secrets-example/github-app-properties.json
          CODEGARTEN_GITHUB_APP_PRIVATE_KEY_PATH: secrets-example/gh-app-private-key.pem
          CODEGARTEN_CIPHER_KEY_PATH: secrets-example/cipher-key.txt
        run: code/jvm/gradlew -p code/jvm test
